### ISSUE TITLE
[bug] Not possible to delete the default `Deployment` with a patch template

### ISSUE THREAD

**Issue by mathieu-benoit** [score-spec/score-k8s#167]
Theorically to delete the default `Deployment` you'll need what we call a patch templates, like this `delete-defaults.tpl`:
```yaml
{{ range $i, $m := .Manifests }}
- op: delete
  path: {{ $i }}
  description: Delete a manifest that was added {{ $m.kind }}
{{ end }}
```

```bash
score-k8s init --patch-templates delete-defaults.tpl

score-k8s generate score.yaml 
```

```none
INFO: Added score file to project
INFO: Primed resources
INFO: Loaded provisioners
INFO: Persisted state file
INFO: Wrote 2 manifests to manifests buffer for workload 'example'
INFO: Applying patching template 1
INFO: Applying patch to 0 (Delete a manifest that was added Service)
INFO: Applying patch to 1 (Delete a manifest that was added Deployment)
INFO: Wrote manifests to 'manifests.yaml'
```

But the generated `manifests.yaml` still have this:
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        k8s.score.dev/workload-name: example
    creationTimestamp: null
    labels:
        app.kubernetes.io/instance: example-160ce9c47e
        app.kubernetes.io/managed-by: score-k8s
        app.kubernetes.io/name: example
    name: example
spec:
    selector:
        matchLabels:
            app.kubernetes.io/instance: example-160ce9c47e
    strategy: {}
    template:
        metadata:
            annotations:
                k8s.score.dev/workload-name: example
            creationTimestamp: null
            labels:
                app.kubernetes.io/instance: example-160ce9c47e
                app.kubernetes.io/managed-by: score-k8s
                app.kubernetes.io/name: example
        spec:
            containers:
                - image: stefanprodan/podinfo
                  name: main
                  resources: {}
status: {}
```
