### ISSUE TITLE
[feature request] Add `--namespace` and `--generate-namespace` flags for `score-k8s generate`

### ISSUE THREAD

**Issue by mathieu-benoit** [score-spec/score-k8s#172]
In order to better support the management and assignment of `Namespace` on Manifests generated or patched by `score-k8s generate`, we need to add the `--namespace` and `--generate-namespace` flags for `score-k8s generate`.

Like `helm install|upgrade` works.
- `--namespace` (optional) will set the `metadata.namespace` field if supplied
- `--generate-namespace` (optional) will actually add a default `Namespace` manifest in the generated `manifests.yaml`, `--namespace` will be required in this case.

We also need to think about how this `--namespace` value is passed through/to the `provisioners` and `patch-templates` for them to set the value if supplied.

Note: if someone wants to patch the generated `Namespace`, they will be able to use a `patch-templates` to inject `annotations`, `labels`, etc.

Implementation details:
- [X] https://github.com/score-spec/score-k8s/pull/176
- [X] https://github.com/score-spec/score-k8s/pull/183
- [X] https://github.com/score-spec/community-patchers/pull/17
- [X] https://github.com/score-spec/community-patchers/pull/18
- [X] https://github.com/score-spec/docs/pull/191
- [X] https://github.com/score-spec/score-k8s/pull/187
- [X] https://github.com/score-spec/community-provisioners/pull/40
- [X] https://github.com/score-spec/score-k8s/pull/190

**Comment by Yadavanurag13** [comment]
@mathieu-benoit I would like to pick this issue.

**Comment by mathieu-benoit** [comment]
Sure thing, @Yadavanurag13, thank you!

Please do let us know if you have any questions or need any clarification!

**Comment by Yadavanurag13** [comment]
@mathieu-benoit Sure. I'll go through more deeply and let u know.

**Comment by mathieu-benoit** [comment]
@Yadavanurag13, I meant to share more context and guidance about the success criterias for what could be a good first PR to tackle most of this feature request (we will see if the rest will be in a second PR or in this one later).

After an initial `score-k8s init`, top of mind, here are 4 main use cases/unit tests.

## 1. First, this should still work (validating that these new parameters are optional, not changing the current behavior):
```bash
score-k8s generate score.yaml
```
```none
INFO: Added score file to project
INFO: Primed resources
INFO: Loaded provisioners
INFO: Persisted state file
INFO: Wrote 2 manifests to manifests buffer for workload 'example'
INFO: Wrote manifests to 'manifests.yaml'
```
```bash
cat manifests.yaml
```
```yaml
---
apiVersion: v1
kind: Service
metadata:
    annotations:
        k8s.score.dev/workload-name: example
    creationTimestamp: null
    labels:
        app.kubernetes.io/instance: example-b71317f5bf
        app.kubernetes.io/managed-by: score-k8s
        app.kubernetes.io/name: example
    name: example
spec:
    ports:
        - name: web
          port: 8080
          protocol: TCP
          targetPort: 8080
    selector:
        app.kubernetes.io/instance: example-b71317f5bf
status:
    loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        k8s.score.dev/workload-name: example
    creationTimestamp: null
    labels:
        app.kubernetes.io/instance: example-b71317f5bf
        app.kubernetes.io/managed-by: score-k8s
        app.kubernetes.io/name: example
    name: example
spec:
    selector:
        matchLabels:
            app.kubernetes.io/instance: example-b71317f5bf
    strategy: {}
    template:
        metadata:
            annotations:
                k8s.score.dev/workload-name: example
            creationTimestamp: null
            labels:
                app.kubernetes.io/instance: example-b71317f5bf
                app.kubernetes.io/managed-by: score-k8s
                app.kubernetes.io/name: example
        spec:
            containers:
                - image: stefanprodan/podinfo
                  name: main
                  resources: {}
status: {}
```

## 2. Second, using `--namespace test-ns` should do this:
```bash
score-k8s generate score.yaml --namespace test-ns
```
```none
INFO: Added score file to project
INFO: Primed resources
INFO: Loaded provisioners
INFO: Persisted state file
INFO: Wrote 2 manifests to manifests buffer for workload 'example'
INFO: Wrote manifests to 'manifests.yaml'
```

```bash
cat manifests.yaml
```
```diff
---
apiVersion: v1
kind: Service
metadata:
    annotations:
        k8s.score.dev/workload-name: example
    creationTimestamp: null
    labels:
        app.kubernetes.io/instance: example-b71317f5bf
        app.kubernetes.io/managed-by: score-k8s
        app.kubernetes.io/name: example
    name: example
+  namespace: test-ns
spec:
    ports:
        - name: web
          port: 8080
          protocol: TCP
          targetPort: 8080
    selector:
        app.kubernetes.io/instance: example-b71317f5bf
status:
    loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        k8s.score.dev/workload-name: example
    creationTimestamp: null
    labels:
        app.kubernetes.io/instance: example-b71317f5bf
        app.kubernetes.io/managed-by: score-k8s
        app.kubernetes.io/name: example
    name: example
+  namespace: test-ns
spec:
    selector:
        matchLabels:
            app.kubernetes.io/instance: example-b71317f5bf
    strategy: {}
    template:
        metadata:
            annotations:
                k8s.score.dev/workload-name: example
            creationTimestamp: null
            labels:
                app.kubernetes.io/instance: example-b71317f5bf
                app.kubernetes.io/managed-by: score-k8s
                app.kubernetes.io/name: example
        spec:
            containers:
                - image: stefanprodan/podinfo
                  name: main
                  resources: {}
status: {}
```

## 3. Third, using `--namespace test-ns --generate-namespace` should do this:
```bash
score-k8s generate score.yaml --namespace test-ns --generate-namespace
```
```diff
INFO: Added score file to project
INFO: Primed resources
INFO: Loaded provisioners
INFO: Persisted state file
- INFO: Wrote 2 manifests to manifests buffer for workload 'example'
+ INFO: Wrote 3 manifests to manifests buffer for workload 'example'
INFO: Wrote manifests to 'manifests.yaml'
```

```bash
cat manifests.yaml
```
```diff
+ ---
+ apiVersion: v1
+ kind: Namespace
+ metadata:
+   labels:
+     app.kubernetes.io/managed-by: score-k8s
+   name: test-ns
---
apiVersion: v1
kind: Service
metadata:
    annotations:
        k8s.score.dev/workload-name: example
    creationTimestamp: null
    labels:
        app.kubernetes.io/instance: example-b71317f5bf
        app.kubernetes.io/managed-by: score-k8s
        app.kubernetes.io/name: example
    name: example
+  namespace: test-ns
spec:
    ports:
        - name: web
          port: 8080
          protocol: TCP
          targetPort: 8080
    selector:
        app.kubernetes.io/instance: example-b71317f5bf
status:
    loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        k8s.score.dev/workload-name: example
    creationTimestamp: null
    labels:
        app.kubernetes.io/instance: example-b71317f5bf
        app.kubernetes.io/managed-by: score-k8s
        app.kubernetes.io/name: example
    name: example
+  namespace: test-ns
spec:
    selector:
        matchLabels:
            app.kubernetes.io/instance: example-b71317f5bf
    strategy: {}
    template:
        metadata:
            annotations:
                k8s.score.dev/workload-name: example
            creationTimestamp: null
            labels:
                app.kubernetes.io/instance: example-b71317f5bf
                app.kubernetes.io/managed-by: score-k8s
                app.kubernetes.io/name: example
        spec:
            containers:
                - image: stefanprodan/podinfo
                  name: main
                  resources: {}
status: {}
```

## 4. Fourth, using `--generate-namespace` (without `--namespace`) should do this:
```bash
score-k8s generate score.yaml --generate-namespace
```
```none
Error: failed to convert 'score.yaml' because --create-namespace was used but --namespace was not provided
```

The idea in this first PR is to implement this and add the associated unit tests please. We may have missed some aspects around that, so please if you have any doubt or need clarification, again, please do let us know, it will be our pleasure to support you on this.

Thanks again for raising your hand for this one, this is an important feature reported by the end-users of this CNCF Sandbox project, so your contribution will have a huge impact out there!
