### ISSUE TITLE
[feature request] Add a default `mssql` provisioner

### ISSUE THREAD

**Issue by mathieu-benoit** [score-spec/score-k8s#66]
Let's add a default `mssql` provisioner, with `outputs`:
- `connection`

For reference:
- https://mcr.microsoft.com/artifact/mar/mssql/server/about
- https://github.com/microsoft/mssql-docker/tree/master

Not tested, but this could be a good starting point:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql-secret
              key: SA_PASSWORD 
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: mssql-data
```

```
apiVersion: v1
kind: Service
metadata:
  name: mssql-service
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP
```

```
apiVersion: v1
kind: Secret
metadata:
  name: mssql-secret
data:
  SA_PASSWORD: FIXME_TO_GENERATE_IN_PROVISIONER
```

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
```

Need to be adapted and tested, file to update https://github.com/score-spec/score-k8s/blob/main/internal/provisioners/default/zz-default.provisioners.yaml.
